### ISSUE TITLE
gulp-install doesn't seems to work with deep deps

### ISSUE THREAD

**Issue by JoMas971** [slushjs/gulp-install#35]
Hello,

I've just install this lib to be able to install deps programatically, so i've a package.json file that will be used to install my deps, but i have always an error (even if i uninstall then re-install everything) : 

```
[18:00:58] 'cordova:create' errored after 3.4 ms
[18:00:58] Error: Cannot find module './lib/_stream_transform.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/iJhon/Sites/iland/ecs-portal/node_modules/gulp-cordova-create/node_modules/through2/node_modules/readable-stream/transform.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/iJhon/Sites/iland/ecs-portal/node_modules/gulp-cordova-create/node_modules/through2/through2.js:1:79)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

I've taken a look inside the `/Users/iJhon/Sites/iland/ecs-portal/node_modules/gulp-cordova-create/node_modules/through2/node_modules/readable-stream/lib` and it seems that there is some of the files missing. I've tried with other lib, and again, some files are missing... Most of the times its the deps of the plugin that is missing.

But if i install the `gulp-cordova-create` lib manually with npm, it works well. Only if i install it with this lib it doesn't install all the files/deep deps (weird...). 

Any ideas ? 

Thanks.

**Comment by JoMas971** [comment]
Ok, i figured out that the issue was caused by my VPN connection. So nothing to do with this lib :-).

Closing the issue.
